
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was ccapConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# ccap Package Configuration File

include(CMakeFindDependencyMacro)

# Include the target definitions
include("${CMAKE_CURRENT_LIST_DIR}/ccapTargets.cmake")

# For MSVC, ensure proper debug/release library selection
if(WIN32 AND MSVC)
    # CMake will automatically handle the debug suffix when using the imported target
    # The ccapTargets.cmake file generated by install(EXPORT) will handle this automatically
endif()

# Set variables for compatibility
set(CCAP_LIBRARIES ccap::ccap)
set(CCAP_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
set(CCAP_FOUND TRUE)

# Check if all required components are available
check_required_components(ccap)

# Print information when found
if(NOT ccap_FIND_QUIETLY)
    message(STATUS "Found ccap: ${CMAKE_CURRENT_LIST_DIR}")
    message(STATUS "  Version: 1.7.4")
    message(STATUS "  Libraries: ${CCAP_LIBRARIES}")
    message(STATUS "  Include dirs: ${CCAP_INCLUDE_DIRS}")
endif()
